config/routes.rb
Rails.application.routes.draw do
  resources :user,only:[:new,:create,:index] do
    collection do
      match '/login' => 'user#login',via:[:get]
      match 'authentication' => 'user#auth', via: [:post]
    end
  end
  namespace :account do
    resources :profile,only: [:index] do
      collection do
        match '/logout' => 'profile#destroy',via:[:get]
      end
      resources :transactions,only: [:index,:new,:create] do
        collection do
          match '/external' => 'transactions#external', via:[:get]
          match '/join' => 'transactions#join',via:[:get]
        end
      end
      resources :group,only: [:index,:new,:create] do
        match '/join' => 'group#join', via:[:get]
        match '/transactions'=>'group#grouptransactions',via:[:get]
        match '/add' => 'group#add', via:[:get]
        match '/added' => 'group#added',via:[:post]
        
      end
    end
  end

  root "user#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :partircpent
  belongs_to :user
  has_many :particpents
  has_many :groupmembers
  has_one_attached :cover_pic

  private

  def partircpent
    particpents.create(user_id: user_id)
  end
end

app/models/groupmember.rb
class Groupmember < ApplicationRecord
  belongs_to :group
  belongs_to :transactin
end

app/models/particpent.rb
class Particpent < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/transactin.rb
class Transactin < ApplicationRecord
  belongs_to :user
  has_many :groupmembers
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactins
  has_many :groups
  has_many :particpents
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/account/base_controller.rb
class Account::BaseController < ApplicationController
  before_action :check_session
  def current_user
    User.find(session[:current_user])
  end
  helper_method :current_user

  private

  def check_session
    redirect_to user_index_path if session[:current_user].nil?
  end
end

app/controllers/account/group_controller.rb
class Account::GroupController < Account::BaseController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    if Group.exists?(name: group_param['name'])
      flash[:msg] = 'Group already exists'
      redirect_to new_account_profile_group_path(session[:current_user])
    else
      @new_group = current_user.groups.create(group_param)
      redirect_to account_profile_index_path(session[:current_user])
    end
  end

  def grouptransactions
    @result = Transactin.where(id: Groupmember.where(group_id: params[:group_id]))
  end

  def join
    res = Particpent.exists?(user_id: session[:current_user], group_id: params[:group_id])
    if res
      obj = Particpent.where(user_id: session[:current_user], group_id: params[:group_id])
      Particpent.destroy(obj.ids)
    else
      Particpent.create(user_id: session[:current_user], group_id: params[:group_id])
    end
    redirect_to account_profile_group_index_path(session[:current_user])
  end

  def add
    @tr = current_user.transactins.all
  end

  def added
    if Groupmember.exists?(Transactin_id: params[:t_id], group_id: params[:group_id])
      obj = Groupmember.where(Transactin_id: params[:t_id], group_id: params[:group_id])
      Groupmember.destroy(obj.ids)
    else
      obj = Groupmember.new(transactin_id: params[:t_id], group_id: params[:group_id])
      obj.save
    end
    redirect_to account_profile_index_path
  end

  private

  def group_param
    params.require(:group).permit(:name, :cover_pic)
  end
end

app/controllers/account/profile_controller.rb
class Account::ProfileController < Account::BaseController
  def index
    @user = User.new
  end

  def destroy
    session[:current_user] = nil
    session[:user_email] = nil
    session[:user_name] = nil
    session[:pic_url] = nil
    redirect_to user_index_path
  end
end

app/controllers/account/transactions_controller.rb
class Account::TransactionsController < Account::BaseController
  def index
    @tran = Transactin.includes(:user).where(user_id: session[:current_user]).order('name ASC')
  end

  def new
    @transac = Transactin.new
  end

  def create
    if current_user.transactins.exists?(transaction_param)
      flash[:msg] = 'Transaction exists'
      new_account_profile_transaction_path(session[:current_user])
    else
      @transac = current_user.transactins.create(transaction_param)
      redirect_to account_profile_transactions_path(session[:current_user])
    end
  end

  def external
    a = Transactin.includes(:user).where(user_id: session[:current_user])
    @external = a.where.not(id: Groupmember.all.select('transactin_id')).order('name ASC')
  end

  def join
    @groups = Group.all
  end

  private

  def transaction_param
    params.permit(:name, :amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :check_session
  def index; end

  def def(_new)
    @user = User.new
  end

  def create
    if params[:password] != params[:cpassword] || User.exists?(user_param)
      flash[:msg] = 'Wrong input'
      redirect_to new_user_path
    else
      @user = User.new(user_param)
      @user.save
      create_session(@user.id, params[:name], params[:email])
      # byebug
      redirect_to account_profile_index_path
    end
  end

  def login
    @user = User.new
  end

  def auth
    if User.exists?(email: params[:email], password: params[:password])
      id = User.where(email: params[:email], password: params[:password])

      create_session(id[0].id, id[0].name, id[0].email, id[0].pic_url)
      redirect_to account_profile_index_path
    else
      flash[:msg] = 'Invalid Username or Password'
      redirect_to login_user_index_path
    end
  end

  private

  def create_session(id = '', name = '', email = '', url = 'logo.jpeg')
    session[:current_user] = id
    session[:user_email] = email
    session[:user_name] = name
    session[:pic_url] = url
  end

  def login_params
    params.require(:user).permit(:email, :password)
  end

  def user_param
    params.permit(:name, :email, :password)
  end

  def check_session
    redirect_to account_profile_index_path unless session[:current_user].nil?
  end
end

app/helpers/account/group_helper.rb
module Account::GroupHelper
  def isjoined(userid, groupid)
    result = Particpent.exists?(user_id: userid, group_id: groupid)
    return 'join' unless result

    'Leave'
  end

  def groupsmeb(group_id, t_id)
    result = Groupmember.exists?(group_id: group_id, transactin_id: t_id)
    return 'Join' unless result

    'Remove'
  end
end

app/helpers/account/profile_helper.rb
module Account::ProfileHelper
end

app/helpers/account/transactions_helper.rb
module Account::TransactionsHelper
  def img_link(tid)
    if Groupmember.exists?(transactin_id: tid)
      obj = Groupmember.where(transactin_id: tid).first
      grou = Group.where(id: obj.group_id).first
      image_tag(url_for(grou.cover_pic), class: 'img')
    else
      link_to 'Join Group', join_account_profile_transactions_path(session[:current_user],
                                                                   t_id: tid), class: 'text-body badge btn btn-success'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/b124683f80.js" crossorigin="anonymous"></script>
  </head>
  <body class="text-white <%=controller_name%>">

    <%= yield %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/user/index.html.erb
<main class="container align-middle mt-lg-5 mt4 user-main">
    <div class="btm">
    <h3 class="pb-4 pt-3 text-center font-weight-bold">Snapscan</h3>
    <a href="<%= login_user_index_path %>" class="btn btn-primary container">login</a><br>
    <a href="<%= new_user_path %>" class="btn btn-primary container mt-2">signup</a>
    </div>
</main>

app/views/user/login.html.erb
<main class="text-center user-main">
<div class="clearfix p-2 ">
    <a href="<%= new_user_path %>" class="float-right badge">Create Account</a>
    <a href="<%=user_index_path%>" class="float-left badge"><i class="fas fa-arrow-left font-weight-bold"></i></a>
    </div>
    <h3 class="pb-4 pt-3 text-center font-weight-bold">Snapscan</h3>
    <form action="<%= authentication_user_index_path %>" method="POST" class="container">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="form-group">
        <input name="email" type="email" class="form-control" required placeholder="Enter email" id="email">
      </div>
      <div class="form-group">
        <input name="password" type="password" class="form-control" required placeholder="Enter password" id="pwd">
      </div>
      <div class="form-group">
      <%if !flash[:msg].nil?%>
      <span class="alert alert-danger"><%=flash[:msg]%></span>
    <%end%>
    </div>
      <button type="submit" name="commit" class="btn btn-primary container pt-1">Submit</button>

    </form>
</main>

app/views/user/new.html.erb
<main class="text-center user-main">
    <div class="clearfix p-2 ">
    <a href="<%= login_user_index_path %>" class="float-right badge">Log In</a>
    <a href="<%=user_index_path%>" class="float-left badge"><i class="fas fa-arrow-left font-weight-bold"></i></a>
    </div>
    <h3 class="pb-4 pt-3 text-center font-weight-bold">Snapscan</h3>
    
    <form action="<%= user_index_path %>" method="POST" class="container">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="form-group">
        <input name="name" type="text" class="form-control" required placeholder="Enter name" id="name">
      </div>
      <div class="form-group">
        <input name="email" type="email" class="form-control" required placeholder="Enter email" id="email">
      </div>
      <div class="form-group">
        <input name="password" type="password" class="form-control" required placeholder="Enter password" id="pwd">
      </div>
      <div class="form-group">
        <input name="cpassword" type="password" class="form-control" required placeholder="confirm password" id="cpwd">
      </div>
    <div class="form-group">
      <%if !flash[:msg].nil?%>
      <span class="alert alert-danger"><%=flash[:msg]%></span>
    <%end%>
    </div>
      <button type="submit" name="commit" class="btn btn-primary container mb-1">Submit</button>

    </form>
</main>